# Generated by Django 3.2.13 on 2022-04-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripincome',
            name='trip_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
