# Generated by Django 3.2.9 on 2022-04-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_dailyincome_weeklyincome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyincome',
            name='amount',
        ),
        migrations.AddField(
            model_name='dailyincome',
            name='income',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
