# Generated by Django 3.2.9 on 2022-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_auto_20220429_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincome',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='decreaseincome',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='increaseincome',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='tripincome',
            name='trip_date',
            field=models.DateField(auto_created=True),
        ),
    ]
